# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 41cf03760ce5bc3c182d7ad720e36301b420f6f14803f408ca6e5c8364a75631e7ef0bfab2d1cf2336c044b00dcb4b9c7146039d9453e1865895471d092daff0

test:
  secret_key_base: f1b942e80d47089842c00e1c04657b9458d9312b35fdaefbaa50fc9333e971e92116fd7ba97b93b7342f724a14ee3815ce813e6dca967de3f4fc4e5e9b4b8f37

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
